### ISSUE TITLE
DockerHub username

### ISSUE THREAD

**Issue by effigies** [nipreps/buildx-repro#1]
@oesteban Do you know what username belongs to the `DOCKER_TOKEN` in nipreps secrets?

For context, I'm trying to build fmriprep on GHA (https://github.com/nipreps/fmriprep/pull/3379), but caching is for some reason hitting DockerHub. I want to see what actually happens when a cache is pushed. If it doesn't have the potential to cause user confusion, I'll just login and let it do it.

**Comment by oesteban** [comment]
nipreps

**Comment by effigies** [comment]
Didn't work.

```
Run docker/login-action@v3
  with:
    username: nipreps
    password: ***
    ecr: auto
    logout: true
  env:
    REGISTRY: ghcr.io
    IMAGE_NAME: nipreps/buildx-repro
Logging into Docker Hub...
Error: Error response from daemon: Get "https://registry-1.docker.io/v2/": unauthorized: incorrect username or password
```

(You can ignore `REGISTRY`, that's just a global env, but not actually used by the action.)

**Comment by oesteban** [comment]
Perhaps it's the token outdated?

**Comment by oesteban** [comment]
Scratch that - speedy fingers and sloppy brain. The username is niprepsbot

**Comment by effigies** [comment]
That worked. Thanks!
